version: '3.9'
services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    networks:
      distr_network:
        ipv4_address: 177.17.0.10
    ports:
      - '3000:3000'

networks:
  distr_network:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 177.17.0.0/16
