version: '3.9'
name: 'distr_chat'
services:

  application_server_1:
    container_name: Application_Server_1
    build:
      dockerfile: ./Application Server/Dockerfile_for_Compose
    volumes:
      - ./Application_Server:/src
    networks:
      distr_network:
        ipv4_address: 177.17.0.20
    ports:
      - '5000:80'
    depends_on:
      - redis_cluster

  application_server_2:
    container_name: Application_Server_2
    build:
      dockerfile: ./Application Server/Dockerfile_for_Compose
    volumes:
      - ./Application_Server:/src
    networks:
      distr_network:
        ipv4_address: 177.17.0.21
    ports:
      - '5001:80'
    depends_on:
      - application_server_1

  frontend:
    container_name: Frontend
    build:
      dockerfile: ./Frontend/Dockerfile
    volumes:
      - ./Frontend:/src
    networks:
      distr_network:
        ipv4_address: 177.17.0.10
    ports:
      - '3000:3000'
    depends_on:
      - application_server_2

  redis_cluster:
      container_name: Backplane_Cluster_Starter
      image: 'redis:7.0.8'
      command: bash -c "redis-cli --cluster create 177.17.0.31:6371 177.17.0.32:6372 177.17.0.33:6373 177.17.0.34:6374 177.17.0.35:6375 177.17.0.36:6376 --cluster-replicas 1 --cluster-yes && trap ':' TERM INT; sleep infinity & wait"
      #&& sleep 10 && redis-cli --cluster call 177.17.0.31:6371 CLUSTER NODES 
      tty: true
      networks:
        distr_network:
          ipv4_address: 177.17.0.30
      depends_on:
        - redis_node_6

  redis_node_1:
      container_name: Backplane_1
      image: 'redis:7.0.8'
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - '6371:6371'
      volumes:
        - redis_node_1-data:/var/lib/redis
        - ./Backplane/Cluster/redis_node_1.conf:/usr/local/etc/redis/redis.conf
      networks:
        distr_network:
          ipv4_address: 177.17.0.31
  redis_node_2:
      container_name: Backplane_2
      image: 'redis:7.0.8'
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - '6372:6372'
      volumes:
        - redis_node_2-data:/var/lib/redis
        - ./Backplane/Cluster/redis_node_2.conf:/usr/local/etc/redis/redis.conf
      networks:
        distr_network:
          ipv4_address: 177.17.0.32
      depends_on:
        - redis_node_1
  redis_node_3:
      container_name: Backplane_3
      image: 'redis:7.0.8'
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - '6373:6373'
      volumes:
        - redis_node_3-data:/var/lib/redis
        - ./Backplane/Cluster/redis_node_3.conf:/usr/local/etc/redis/redis.conf
      networks:
        distr_network:
          ipv4_address: 177.17.0.33
      depends_on:
        - redis_node_2
  redis_node_4:
      container_name: Backplane_4
      image: 'redis:7.0.8'
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - '6374:6374'
      volumes:
        - redis_node_4-data:/var/lib/redis
        - ./Backplane/Cluster/redis_node_4.conf:/usr/local/etc/redis/redis.conf
      networks:
        distr_network:
          ipv4_address: 177.17.0.34
      depends_on:
        - redis_node_3
  redis_node_5:
      container_name: Backplane_5
      image: 'redis:7.0.8'
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - '6375:6375'
      volumes:
        - redis_node_5-data:/var/lib/redis
        - ./Backplane/Cluster/redis_node_5.conf:/usr/local/etc/redis/redis.conf
      networks:
        distr_network:
          ipv4_address: 177.17.0.35
      depends_on:
        - redis_node_4
  redis_node_6:
      container_name: Backplane_6
      image: 'redis:7.0.8'
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - '6376:6376'
      volumes:
        - redis_node_6-data:/var/lib/redis
        - ./Backplane/Cluster/redis_node_6.conf:/usr/local/etc/redis/redis.conf
      networks:
        distr_network:
          ipv4_address: 177.17.0.36
      depends_on:
        - redis_node_5

volumes:
  Frontend:
  Application_Server:
  redis_node_1-data:
  redis_node_2-data:
  redis_node_3-data:
  redis_node_4-data:
  redis_node_5-data:
  redis_node_6-data:

networks:
  distr_network:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 177.17.0.0/16
